name: Bug Report
description: Report a bug in RailsPress
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out the information below to help us investigate.

  - type: input
    id: railspress-version
    attributes:
      label: RailsPress version
      description: Run `bundle show railspress` to find this
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: rails-version
    attributes:
      label: Rails version
      description: Run `rails -v` to find this
      placeholder: "8.0.0"
    validations:
      required: true

  - type: input
    id: ruby-version
    attributes:
      label: Ruby version
      description: Run `ruby -v` to find this
      placeholder: "3.3.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A clear description of what the bug is
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        Detailed steps to reproduce the behavior:
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error logs
      description: Paste any relevant error messages or stack traces
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context about the problem (screenshots, configuration, etc.)
