import { Controller } from "@hotwired/stimulus"

/**
 * CMS Inline Editor Controller
 *
 * Enables right-click inline editing of CMS content elements on live pages.
 * Opens a positioned context menu with a Turbo Frame that lazy-loads an
 * inline edit form from the admin controller.
 *
 * Usage (generated by CmsHelper#inline_wrapper_for):
 *   <span data-controller="rp--cms-inline-editor"
 *         data-rp--cms-inline-editor-inline-path-value="/railspress/admin/content_elements/1/inline"
 *         data-rp--cms-inline-editor-frame-id-value="cms_display_1_abc123"
 *         data-rp--cms-inline-editor-form-frame-id-value="cms_form_1_abc123"
 *         data-rp--cms-inline-editor-element-id-value="1"
 *         data-action="contextmenu->rp--cms-inline-editor#open"
 *         style="display:contents">
 *
 *     <turbo-frame id="cms_display_1_abc123">Content here</turbo-frame>
 *     <div class="rp-inline-menu rp-inline-hidden" data-rp--cms-inline-editor-target="menu">
 *       <turbo-frame id="cms_form_1_abc123" data-rp--cms-inline-editor-target="frame"></turbo-frame>
 *     </div>
 *     <div class="rp-inline-backdrop rp-inline-hidden" data-rp--cms-inline-editor-target="backdrop"></div>
 *   </span>
 */
export default class extends Controller {
  static targets = ["menu", "frame", "backdrop"]

  static values = {
    inlinePath: String,
    frameId: String,
    formFrameId: String,
    elementId: Number,
    loaded: { type: Boolean, default: false }
  }

  connect() {
    this._handleKeydown = this.handleKeydown.bind(this)
    this._handleSubmitEnd = this.handleSubmitEnd.bind(this)
  }

  disconnect() {
    document.removeEventListener("keydown", this._handleKeydown)
    this.element.removeEventListener("turbo:submit-end", this._handleSubmitEnd)
  }

  open(event) {
    event.preventDefault()
    event.stopPropagation()

    // Close any other open inline editors (one-at-a-time)
    document.querySelectorAll(".rp-inline-menu:not(.rp-inline-hidden)").forEach(menu => {
      const controller = this.application.getControllerForElementAndIdentifier(
        menu.closest("[data-controller*='rp--cms-inline-editor']"),
        "rp--cms-inline-editor"
      )
      if (controller && controller !== this) controller.close()
    })

    // Lazy-load the form Turbo Frame on first open
    if (!this.loadedValue && this.hasFrameTarget) {
      const url = new URL(this.inlinePathValue, window.location.origin)
      url.searchParams.set("form_frame_id", this.formFrameIdValue)
      url.searchParams.set("display_frame_id", this.frameIdValue)
      this.frameTarget.setAttribute("src", url.toString())
      this.loadedValue = true
    }

    // Position the menu near the click
    this.positionMenu(event.clientX, event.clientY)

    // Show menu and backdrop
    this.menuTarget.classList.remove("rp-inline-hidden")
    this.backdropTarget.classList.remove("rp-inline-hidden")

    // Listen for escape and form submission
    document.addEventListener("keydown", this._handleKeydown)
    this.element.addEventListener("turbo:submit-end", this._handleSubmitEnd)
  }

  close() {
    this.menuTarget.classList.add("rp-inline-hidden")
    this.backdropTarget.classList.add("rp-inline-hidden")
    document.removeEventListener("keydown", this._handleKeydown)
    this.element.removeEventListener("turbo:submit-end", this._handleSubmitEnd)
  }

  handleKeydown(event) {
    if (event.key === "Escape") {
      event.preventDefault()
      this.close()
    }
  }

  handleSubmitEnd(event) {
    if (event.detail.success) {
      this.close()
      // Reload the frame on next open to get fresh data
      this.loadedValue = false
    }
  }

  positionMenu(x, y) {
    const menu = this.menuTarget
    // Reset position to measure natural dimensions
    menu.style.left = "0px"
    menu.style.top = "0px"
    menu.classList.remove("rp-inline-hidden")

    const rect = menu.getBoundingClientRect()
    const padding = 8

    // Constrain within viewport
    let left = x
    let top = y

    if (left + rect.width + padding > window.innerWidth) {
      left = window.innerWidth - rect.width - padding
    }
    if (left < padding) left = padding

    if (top + rect.height + padding > window.innerHeight) {
      top = window.innerHeight - rect.height - padding
    }
    if (top < padding) top = padding

    menu.style.left = `${left}px`
    menu.style.top = `${top}px`
  }
}
